<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.zupix</groupId>
        <artifactId>zupix-parent</artifactId>
        <version>0.1.0</version>
    </parent>
    <artifactId>zupix-cli</artifactId>
    <name>Zupix CLI</name>
    <dependencies>
        <dependency><groupId>io.zupix</groupId><artifactId>zupix-core</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
    </dependencies>
    <build>
        <plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-jar-plugin</artifactId></plugin></plugins>
    </build>
</project>
